_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
                - 95
                - 100
            "2":
                - 1
                - 55
                - 95
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 6
            "12": 0.19.1
            "13": darwin-x86_64
